# Generated by Django 4.2.7 on 2023-11-06 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_exercise_id', models.IntegerField()),
                ('external_exercise_name', models.CharField(max_length=100)),
                ('personal_best', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('session_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight_kg', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog_Exercise',
            fields=[
                ('session_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionlog')),
            ],
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
