# Generated by Django 4.2.7 on 2023-11-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('session_name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog_Exercise',
            fields=[
                ('session_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionlog')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight_kg', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
