# Generated by Django 4.2.7 on 2023-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='external_exercise_bodypart',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
